X20:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 400

  LF_HAA_controller:
    joint: A_LF_HAA
    type: effort_controllers/JointEffortController

  LF_HFE_controller:
    joint: A_LF_HFE
    type: effort_controllers/JointEffortController

  LF_KFE_controller:
    joint: A_LF_KFE
    type: effort_controllers/JointEffortController

  RF_HAA_controller:
    joint: A_RF_HAA
    type: effort_controllers/JointEffortController

  RF_HFE_controller:
    joint: A_RF_HFE
    type: effort_controllers/JointEffortController

  RF_KFE_controller:
    joint: A_RF_KFE
    type: effort_controllers/JointEffortController

  LH_HAA_controller:
    joint: B_LH_HAA
    type: effort_controllers/JointEffortController

  LH_HFE_controller:
    joint: B_LH_HFE
    type: effort_controllers/JointEffortController

  LH_KFE_controller:
    joint: B_LH_KFE
    type: effort_controllers/JointEffortController
    
  RH_HAA_controller:
    joint: B_RH_HAA
    type: effort_controllers/JointEffortController

  RH_HFE_controller:
    joint: B_RH_HFE
    type: effort_controllers/JointEffortController

  RH_KFE_controller:
    joint: B_RH_KFE
    type: effort_controllers/JointEffortController




  
